version: "3.9"

services:
  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev  # Uses a dev Dockerfile for hot reload
    volumes:
      - ./frontend:/app  # Sync local frontend folder for hot-reloading
      - /app/node_modules
    networks:
      - internal_network
    depends_on:
      - backend

  backend:
    container_name: backend
    build:
      context: ./backend
      dockerfile: Dockerfile.dev  # Dev Dockerfile for fast iteration
    environment:
      FLASK_ENV: "development"
      JWT_SECRET_KEY: "dev_secret_key"
      MONGO_URI: "mongodb+srv://robinrettien:uZyJE7EfSKlWnVnd@vintedscraper.eqode.mongodb.net/vinted_scraper_db?ssl=true&tlsAllowInvalidCertificates=true"
      SQLALCHEMY_DATABASE_URI: "postgresql://Vinted-Scraper-DB_owner:7lmZUxpw4kXJ@ep-silent-recipe-a9x7mnwn.gwc.azure.neon.tech:5432/Vinted-Scraper-DB?sslmode=require"
      GOOGLE_SECRET: "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"
      GOOGLE_CLIENT: "1007725109700-h9go6r2e7bosait1f8u01sru5kqt7rdn.apps.googleusercontent.com"
    ports:
      - "5000:5000"  # Expose backend
    volumes:
      - ./backend:/app  # Sync backend files for hot-reloading
    networks:
      - internal_network

  scraper:
    container_name: scraper
    build:
      context: ./scrapers
      dockerfile: Dockerfile.dev
    networks:
      - internal_network
    depends_on:
      - backend

  nginx:
    container_name: nginx
    image: nginx:latest
    ports:
      - "4430:4430"
      - "8080:8080"
    volumes:
      - ./nginx/development/nginx.conf:/etc/nginx/nginx.conf:ro    
      - ./nginx/development/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - backend
      - frontend
    networks:
      - internal_network

networks:
  internal_network:
    driver: bridge

