"""Add one-to-one relationships for MainCategory and SubCategory

Revision ID: ba126a905adc
Revises: 23d88932d371
Create Date: 2024-12-17 10:10:17.401290

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ba126a905adc'
down_revision = '23d88932d371'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('main_categories',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('gender', sa.String(length=10), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('subcategories',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('gender', sa.String(length=10), nullable=False),
    sa.Column('main_category_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['main_category_id'], ['main_categories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('channels', schema=None) as batch_op:
        batch_op.add_column(sa.Column('main_category_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('sub_category_id', sa.Integer(), nullable=True))
        batch_op.create_unique_constraint(None, ['sub_category_id'])
        batch_op.create_unique_constraint(None, ['main_category_id'])
        batch_op.create_foreign_key(None, 'main_categories', ['main_category_id'], ['id'])
        batch_op.create_foreign_key(None, 'subcategories', ['sub_category_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('channels', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('sub_category_id')
        batch_op.drop_column('main_category_id')

    op.drop_table('subcategories')
    op.drop_table('main_categories')
    # ### end Alembic commands ###
