"""Added query_identifier to the channel model to handle proper get requests

Revision ID: dcfbed6eb9ed
Revises: 40f0bd67eb65
Create Date: 2024-12-19 12:20:10.656010

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dcfbed6eb9ed'
down_revision = '40f0bd67eb65'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('channels', schema=None) as batch_op:
        batch_op.add_column(sa.Column('query_identifier', sa.Integer(), nullable=False))
        batch_op.create_unique_constraint(None, ['query_identifier'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('channels', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('query_identifier')

    # ### end Alembic commands ###
